# Generated by Django 2.2 on 2022-11-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_item_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
