# Generated by Django 2.2 on 2022-11-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221118_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ES', 'Especias'), ('FR', 'Frutería'), ('CN', 'Carnicería'), ('PE', 'Pescadería')], max_length=2),
        ),
    ]
