# Generated by Django 2.2 on 2022-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221118_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Frutas'), ('SW', 'Especias'), ('OW', 'Vegetales')], max_length=2),
        ),
    ]
