# Generated by Django 2.2 on 2022-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221118_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Frutería'), ('SW', 'Pescaderia'), ('OW', 'Carniceria')], max_length=2),
        ),
    ]
