# Generated by Django 2.2 on 2022-11-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20221126_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='tittle',
            new_name='title',
        ),
    ]
