# Generated by Django 2.2 on 2022-11-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20221126_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='responses',
        ),
        migrations.AddField(
            model_name='response',
            name='opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion', to='core.Opinion'),
        ),
    ]
