# Generated by Django 2.2 on 2022-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20221127_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='disponibility',
            field=models.CharField(choices=[('D', 'Disponible'), ('ND', 'No disponible')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_metod',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
