# Generated by Django 2.2 on 2022-11-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20221130_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_metod',
            new_name='shipping_method',
        ),
    ]
