# Generated by Django 2.2 on 2022-11-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20221130_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_method',
            new_name='shipping',
        ),
    ]
